  - name: codeql-summarize
  # You may pin to the exact commit or the version.
  # uses: advanced-security/codeql-summarize@6fc479bff10de3988e8d783a229b367b530afd6d
    uses: advanced-security/codeql-summarize@v0.2.0
     with:
    # Project Repo (owner/name)
    project: # optional
    # Project File with projects
    projects: # optional, default is ./projects.json
    # Project Language
    language: # optional
    # Exporting Format (default: bundle)
    format: # optional, default is extensions
    # Output Directory
    output: # optional, default is ./
    # GitHub Repository
    repository: # optional, default is ${{ github.repository }}
    # GitHub Personal Access Token
    token: # optional, default is ${{ github.token }}
          
